Readme file for settings in the input.pro file

Region selection
; regions can be selected in group via a range of region-IDs
; (diverging from RGI region IDs due to subregions)
; alternatively regions can also be directly selected by putting region_id_loop=[0,0]	
; individual regions / subregions to be run (mostly working with region-loop)
;dir_region='Alaska' & region_n=['alaska']  ; *1
;dir_region='WesternCanada' & region_n=['westerncanada']    ; *2
;dir_region='ArcticCanadaN' & region_n=['arcticcanadaN']   ; *3
;dir_region='ArcticCanadaS' & region_n=['arcticcanadaS']   ; *4
;dir_region='Greenland' & region_n=['greenland']           ; *5
;dir_region='Iceland' & region_n=['iceland']                ; *6
;dir_region='Svalbard' & region_n=['svalbard']             ; *7
;dir_region='Scandinavia' & region_n=['scandinavia']      ; *8
;dir_region='RussianArctic' & region_n=['russianarctic']   ; *9
;dir_region='NorthAsia' & region_n=['northasia']  & clim_subregion='Altay'; *10
;dir_region='NorthAsia' & region_n=['northasia']  & clim_subregion='Chukotka'; *11
;dir_region='NorthAsia' & region_n=['northasia']  & clim_subregion='East'; *12
;dir_region='NorthAsia' & region_n=['northasia']  & clim_subregion='North'; *13
;dir_region='CentralEurope' & region_n=['centraleurope']  ; *14
;dir_region='Caucasus' & region_n=['caucasus']            ; *15
;dir_region='CentralAsia' & region_n=['centralasiaN']  ; *16
;dir_region='SouthAsiaWest' & region_n=['centralasiaW'] ; *17
;dir_region='SouthAsiaEast' & region_n=['centralasiaS'] ; *18
;dir_region='LowLatitudes' & region_n=['lowlatitudes'] & clim_subregion='Andes'; *19
;dir_region='LowLatitudes' & region_n=['lowlatitudes'] & clim_subregion='Africa'; *20
;dir_region='LowLatitudes' & region_n=['lowlatitudes'] & clim_subregion='Mexico'; *21
;dir_region='LowLatitudes' & region_n=['lowlatitudes'] & clim_subregion='Newguinea' ; *22
;dir_region='SouthernAndes' & region_n=['southernandes']  ; *23
;dir_region='NewZealand' & region_n=['newzealand']       ; *24
;dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='Atlantic'; *25
;dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='Indian'; *26
;dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='Pacific'; *27
;dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='MaudWilkes'; *28
;dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='Victoria'; *29
;dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='Peninsula'; *30
; dir_region='Antarctic' & region_n=['antarctic'] & clim_subregion='MarieByrd'; *31


Codes for CMIP6-GCMs
; 1: 'BCC-CSM2-MR', 2: 'CAMS-CSM1-0', 3:'CESM2', 4:'CESM2-WACCM', 5:'EC-Earth3', 6:'EC-Earth3-Veg', 7:'FGOALS-f3-L', 8:'GFDL-ESM4',
; 9:'INM-CM4-8', 10:'INM-CM5-0', 11:'MPI-ESM1-2-HR', 12:'MRI-ESM2-0', 13:'NorESM2-MM'
